/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BreevsRussianRoulette {
  export type SpinRequestStruct = {
    pending: boolean;
    commitBlock: BigNumberish;
    round: BigNumberish;
  };

  export type SpinRequestStructOutput = [
    pending: boolean,
    commitBlock: bigint,
    round: bigint
  ] & { pending: boolean; commitBlock: bigint; round: bigint };
}

export interface BreevsRussianRouletteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PLAYERS"
      | "MAX_ROUND_DURATION"
      | "MAX_STAKE"
      | "MIN_HOST_BALANCE"
      | "MIN_ROUND_DURATION"
      | "MIN_STAKE"
      | "REVEAL_DELAY"
      | "advanceRound"
      | "celoRandomAddress"
      | "claimPrize"
      | "createGame"
      | "gameCounter"
      | "games"
      | "getActivePlayers"
      | "getPendingSpin"
      | "joinGame"
      | "pendingSpins"
      | "playerDeposits"
      | "playerGameData"
      | "prizeClaimed"
      | "randomContract"
      | "requestSpin"
      | "resolveSpin"
      | "startGame"
      | "userStats"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCompleted"
      | "GameCreated"
      | "GameStarted"
      | "PlayerEliminated"
      | "PlayerJoined"
      | "PrizeClaimed"
      | "SpinRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PLAYERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ROUND_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_HOST_BALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_ROUND_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REVEAL_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "advanceRound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "celoRandomAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimPrize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gameCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getActivePlayers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingSpin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingSpins",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerDeposits",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerGameData",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "prizeClaimed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "randomContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSpin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveSpin",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStats",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_PLAYERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ROUND_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_HOST_BALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_ROUND_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REVEAL_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advanceRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "celoRandomAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimPrize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gameCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActivePlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingSpin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingSpins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerGameData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prizeClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSpin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveSpin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStats", data: BytesLike): Result;
}

export namespace GameCompletedEvent {
  export type InputTuple = [gameId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [gameId: bigint, winner: string];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [gameId: BigNumberish];
  export type OutputTuple = [gameId: bigint];
  export interface OutputObject {
    gameId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEliminatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    round: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, round: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [gameId: BigNumberish, player: AddressLike];
  export type OutputTuple = [gameId: bigint, player: string];
  export interface OutputObject {
    gameId: bigint;
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeClaimedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpinRequestedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    commitBlock: BigNumberish,
    round: BigNumberish
  ];
  export type OutputTuple = [
    gameId: bigint,
    commitBlock: bigint,
    round: bigint
  ];
  export interface OutputObject {
    gameId: bigint;
    commitBlock: bigint;
    round: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BreevsRussianRoulette extends BaseContract {
  connect(runner?: ContractRunner | null): BreevsRussianRoulette;
  waitForDeployment(): Promise<this>;

  interface: BreevsRussianRouletteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PLAYERS: TypedContractMethod<[], [bigint], "view">;

  MAX_ROUND_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_STAKE: TypedContractMethod<[], [bigint], "view">;

  MIN_HOST_BALANCE: TypedContractMethod<[], [bigint], "view">;

  MIN_ROUND_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  REVEAL_DELAY: TypedContractMethod<[], [bigint], "view">;

  advanceRound: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  celoRandomAddress: TypedContractMethod<[], [string], "view">;

  claimPrize: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  createGame: TypedContractMethod<
    [stake: BigNumberish, roundDuration: BigNumberish],
    [bigint],
    "payable"
  >;

  gameCounter: TypedContractMethod<[], [bigint], "view">;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        creator: string;
        stake: bigint;
        prizePool: bigint;
        status: bigint;
        roundDuration: bigint;
        roundEnd: bigint;
        currentRound: bigint;
        winner: string;
        totalRounds: bigint;
      }
    ],
    "view"
  >;

  getActivePlayers: TypedContractMethod<
    [gameId: BigNumberish],
    [string[]],
    "view"
  >;

  getPendingSpin: TypedContractMethod<
    [gameId: BigNumberish],
    [BreevsRussianRoulette.SpinRequestStructOutput],
    "view"
  >;

  joinGame: TypedContractMethod<[gameId: BigNumberish], [void], "payable">;

  pendingSpins: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        pending: boolean;
        commitBlock: bigint;
        round: bigint;
      }
    ],
    "view"
  >;

  playerDeposits: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  playerGameData: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, bigint] & { eliminated: boolean; eliminationRound: bigint }],
    "view"
  >;

  prizeClaimed: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  randomContract: TypedContractMethod<[], [string], "view">;

  requestSpin: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveSpin: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "nonpayable"
  >;

  startGame: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  userStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        gamesPlayed: bigint;
        gamesWon: bigint;
        totalWinnings: bigint;
        totalStaked: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PLAYERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ROUND_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_HOST_BALANCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_ROUND_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REVEAL_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "advanceRound"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "celoRandomAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimPrize"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [stake: BigNumberish, roundDuration: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "gameCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        creator: string;
        stake: bigint;
        prizePool: bigint;
        status: bigint;
        roundDuration: bigint;
        roundEnd: bigint;
        currentRound: bigint;
        winner: string;
        totalRounds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActivePlayers"
  ): TypedContractMethod<[gameId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPendingSpin"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [BreevsRussianRoulette.SpinRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "pendingSpins"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        pending: boolean;
        commitBlock: bigint;
        round: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerDeposits"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerGameData"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, bigint] & { eliminated: boolean; eliminationRound: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "prizeClaimed"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "randomContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestSpin"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveSpin"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGame"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        gamesPlayed: bigint;
        gamesWon: bigint;
        totalWinnings: bigint;
        totalStaked: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "GameCompleted"
  ): TypedContractEvent<
    GameCompletedEvent.InputTuple,
    GameCompletedEvent.OutputTuple,
    GameCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEliminated"
  ): TypedContractEvent<
    PlayerEliminatedEvent.InputTuple,
    PlayerEliminatedEvent.OutputTuple,
    PlayerEliminatedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PrizeClaimed"
  ): TypedContractEvent<
    PrizeClaimedEvent.InputTuple,
    PrizeClaimedEvent.OutputTuple,
    PrizeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SpinRequested"
  ): TypedContractEvent<
    SpinRequestedEvent.InputTuple,
    SpinRequestedEvent.OutputTuple,
    SpinRequestedEvent.OutputObject
  >;

  filters: {
    "GameCompleted(uint256,address)": TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;
    GameCompleted: TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;

    "GameCreated(uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameStarted(uint256)": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "PlayerEliminated(uint256,address,uint256)": TypedContractEvent<
      PlayerEliminatedEvent.InputTuple,
      PlayerEliminatedEvent.OutputTuple,
      PlayerEliminatedEvent.OutputObject
    >;
    PlayerEliminated: TypedContractEvent<
      PlayerEliminatedEvent.InputTuple,
      PlayerEliminatedEvent.OutputTuple,
      PlayerEliminatedEvent.OutputObject
    >;

    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "PrizeClaimed(uint256,address,uint256)": TypedContractEvent<
      PrizeClaimedEvent.InputTuple,
      PrizeClaimedEvent.OutputTuple,
      PrizeClaimedEvent.OutputObject
    >;
    PrizeClaimed: TypedContractEvent<
      PrizeClaimedEvent.InputTuple,
      PrizeClaimedEvent.OutputTuple,
      PrizeClaimedEvent.OutputObject
    >;

    "SpinRequested(uint256,uint256,uint256)": TypedContractEvent<
      SpinRequestedEvent.InputTuple,
      SpinRequestedEvent.OutputTuple,
      SpinRequestedEvent.OutputObject
    >;
    SpinRequested: TypedContractEvent<
      SpinRequestedEvent.InputTuple,
      SpinRequestedEvent.OutputTuple,
      SpinRequestedEvent.OutputObject
    >;
  };
}
