/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IRandom, IRandomInterface } from "../IRandom";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
    ],
    name: "getBlockRandomness",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "random",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRandom__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomInterface {
    return new Interface(_abi) as IRandomInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRandom {
    return new Contract(address, _abi, runner) as unknown as IRandom;
  }
}
