/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IRegistry, IRegistryInterface } from "../IRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
    ],
    name: "getAddressFor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IRegistryInterface {
    return new Interface(_abi) as IRegistryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRegistry {
    return new Contract(address, _abi, runner) as unknown as IRegistry;
  }
}
